name: Build Split Containers

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'dockerfiles/**'
      - '.github/workflows/build-split.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'dockerfiles/**'
      - '.github/workflows/build-split.yml'
  workflow_dispatch:
    inputs:
      push_to_registry:
        description: 'Push images to registry'
        required: false
        type: boolean
        default: true

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/jon-babylon

jobs:
  # Build base image first (AMD64 only for dev containers)
  build-base:
    name: Build Base Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/base/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-base:test
            ${{ env.IMAGE_PREFIX }}-base:${{ github.sha }}
          cache-from: type=gha,scope=base
          cache-to: type=gha,mode=max,scope=base,ignore-error=true

      - name: Test base image
        run: |
          docker run --rm ${{ env.IMAGE_PREFIX }}-base:test check_versions.sh

      - name: Push base image
        if: github.event_name != 'pull_request'
        run: |
          docker tag ${{ env.IMAGE_PREFIX }}-base:test ${{ env.IMAGE_PREFIX }}-base:latest
          docker push ${{ env.IMAGE_PREFIX }}-base:latest
          docker push ${{ env.IMAGE_PREFIX }}-base:${{ github.sha }}

  # Build all other containers in parallel (AMD64 only)
  build-containers:
    name: Build ${{ matrix.container }} Container
    needs: build-base
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        container: [jvm, clang, go, web]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.container }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/${{ matrix.container }}/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-${{ matrix.container }}:test
            ${{ env.IMAGE_PREFIX }}-${{ matrix.container }}:${{ github.sha }}
          cache-from: type=gha,scope=${{ matrix.container }}
          cache-to: type=gha,mode=max,scope=${{ matrix.container }},ignore-error=true
          build-args: |
            BASE_IMAGE=${{ env.IMAGE_PREFIX }}-base:${{ github.sha }}

      - name: Test ${{ matrix.container }} image
        run: |
          echo "=== Testing ${{ matrix.container }} container ==="

          # Run version check
          echo "Running version check..."
          docker run --rm ${{ env.IMAGE_PREFIX }}-${{ matrix.container }}:test check_versions.sh

          # Run container-specific tests
          echo "Running container tests..."
          TEST_DIR="dockerfiles/${{ matrix.container }}/tests"

          if [ -d "$TEST_DIR" ]; then
            for test_subdir in "$TEST_DIR"/*; do
              if [ -d "$test_subdir" ] && [ -f "$test_subdir/run_test.sh" ]; then
                TEST_NAME=$(basename "$test_subdir")
                echo "Running $TEST_NAME tests..."

                # Run tests with host user ID to avoid permission issues
                docker run --rm \
                  -u "$(id -u):$(id -g)" \
                  -v "$(pwd)/$test_subdir:/workspace" \
                  -w /workspace \
                  -e HOME=/tmp/home \
                  -e GOPATH=/tmp/go \
                  -e GOCACHE=/tmp/go-cache \
                  -e GRADLE_USER_HOME=/tmp/gradle \
                  -e MAVEN_USER_HOME=/tmp/maven \
                  ${{ env.IMAGE_PREFIX }}-${{ matrix.container }}:test \
                  bash run_test.sh || exit 1

                echo "✓ $TEST_NAME tests passed"
              fi
            done
          else
            echo "No test directory found for ${{ matrix.container }}"
          fi

          echo "✓ All tests passed for ${{ matrix.container }}"

      - name: Push ${{ matrix.container }} image
        if: github.event_name != 'pull_request'
        run: |
          docker tag ${{ env.IMAGE_PREFIX }}-${{ matrix.container }}:test ${{ env.IMAGE_PREFIX }}-${{ matrix.container }}:latest
          docker push ${{ env.IMAGE_PREFIX }}-${{ matrix.container }}:latest
          docker push ${{ env.IMAGE_PREFIX }}-${{ matrix.container }}:${{ github.sha }}

  # Build Python container (depends on Clang, AMD64 only)
  build-python:
    name: Build Python Container
    needs: build-containers
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          echo "=== Disk space before cleanup ==="
          df -h

          echo "=== Cleaning up Docker ==="
          docker system prune -af --volumes

          echo "=== Removing unnecessary files ==="
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          echo "=== Disk space after cleanup ==="
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Python image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/python/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-python:test
            ${{ env.IMAGE_PREFIX }}-python:${{ github.sha }}
          cache-from: type=gha,scope=python
          cache-to: type=gha,mode=max,scope=python,ignore-error=true
          build-args: |
            CLANG_IMAGE=${{ env.IMAGE_PREFIX }}-clang:${{ github.sha }}

      - name: Test Python image
        run: |
          echo "=== Testing Python container ==="

          # Run version check
          echo "Running version check..."
          docker run --rm ${{ env.IMAGE_PREFIX }}-python:test check_versions.sh

          # Run Python-specific tests
          echo "Running Python tests..."
          TEST_DIR="dockerfiles/python/tests"

          if [ -d "$TEST_DIR" ]; then
            for test_subdir in "$TEST_DIR"/*; do
              if [ -d "$test_subdir" ] && [ -f "$test_subdir/run_test.sh" ]; then
                TEST_NAME=$(basename "$test_subdir")
                echo "Running $TEST_NAME tests..."

                # Run tests with host user ID to avoid permission issues
                docker run --rm \
                  -u "$(id -u):$(id -g)" \
                  -v "$(pwd)/$test_subdir:/workspace" \
                  -w /workspace \
                  -e HOME=/tmp/home \
                  -e PYTHONUSERBASE=/tmp/python \
                  -e PIP_CACHE_DIR=/tmp/pip-cache \
                  ${{ env.IMAGE_PREFIX }}-python:test \
                  bash run_test.sh || exit 1

                echo "✓ $TEST_NAME tests passed"
              fi
            done
          else
            echo "No test directory found for Python"
          fi

          echo "✓ All tests passed for Python"

      - name: Push Python image
        if: github.event_name != 'pull_request'
        run: |
          docker tag ${{ env.IMAGE_PREFIX }}-python:test ${{ env.IMAGE_PREFIX }}-python:latest
          docker push ${{ env.IMAGE_PREFIX }}-python:latest
          docker push ${{ env.IMAGE_PREFIX }}-python:${{ github.sha }}

  # Build Rust container (depends on Clang, AMD64 only)
  build-rust:
    name: Build Rust Container
    needs: build-containers
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          echo "=== Disk space before cleanup ==="
          df -h

          echo "=== Cleaning up Docker ==="
          docker system prune -af --volumes

          echo "=== Removing unnecessary files ==="
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL

          echo "=== Disk space after cleanup ==="
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Rust image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/rust/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_PREFIX }}-rust:test
            ${{ env.IMAGE_PREFIX }}-rust:${{ github.sha }}
          cache-from: type=gha,scope=rust
          cache-to: type=gha,mode=max,scope=rust,ignore-error=true
          build-args: |
            CLANG_IMAGE=${{ env.IMAGE_PREFIX }}-clang:${{ github.sha }}

      - name: Test Rust image
        run: |
          echo "=== Testing Rust container ==="

          # Run version check
          echo "Running version check..."
          docker run --rm ${{ env.IMAGE_PREFIX }}-rust:test check_versions.sh

          # Run Rust-specific tests
          echo "Running Rust tests..."
          TEST_DIR="dockerfiles/rust/tests"

          if [ -d "$TEST_DIR" ]; then
            for test_subdir in "$TEST_DIR"/*; do
              if [ -d "$test_subdir" ] && [ -f "$test_subdir/run_test.sh" ]; then
                TEST_NAME=$(basename "$test_subdir")
                echo "Running $TEST_NAME tests..."

                # Run tests with host user ID to avoid permission issues
                docker run --rm \
                  -u "$(id -u):$(id -g)" \
                  -v "$(pwd)/$test_subdir:/workspace" \
                  -w /workspace \
                  -e HOME=/tmp/home \
                  ${{ env.IMAGE_PREFIX }}-rust:test \
                  bash run_test.sh || exit 1

                echo "✓ $TEST_NAME tests passed"
              fi
            done
          else
            echo "No test directory found for Rust"
          fi

          echo "✓ All tests passed for Rust"

      - name: Push Rust image
        if: github.event_name != 'pull_request'
        run: |
          docker tag ${{ env.IMAGE_PREFIX }}-rust:test ${{ env.IMAGE_PREFIX }}-rust:latest
          docker push ${{ env.IMAGE_PREFIX }}-rust:latest
          docker push ${{ env.IMAGE_PREFIX }}-rust:${{ github.sha }}